environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run bootstrap
test_script:
  - node --version
  - npm test
build: off
